# Generated by Django 6.0 on 2025-12-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Room number or name', max_length=20, unique=True)),
                ('capacity', models.IntegerField(help_text='Seating capacity of the room')),
                ('is_available', models.BooleanField(default=True, help_text='Is the room available for exam allocation?')),
            ],
        ),
    ]
